### ISSUE TITLE
wandb error

### ISSUE THREAD

**Issue by bastienmasse** [trackmania-rl/tmrl#71] opened 2023-10-29 09:33 UTC
Hi, I followed the instructions in the tutorial, but when i launch the trainer, i have got this message:
wandb: ERROR Error while calling W&B API: run tmrl/tmrl/SAC_4_imgs_pretrained was previously created and deleted; try a new run name (<Response [409]>)

**Comment by yannbouteiller** [comment] 2023-10-29 14:01
Hi, you need to change the RUN_NAME entry in config.json, or add --no-wandb to your command line:

`python3 -m tmrl --trainer --no-wandb`

**Comment by yannbouteiller** [comment] 2023-10-29 19:49
Closing as this is not a bug, but in version `0.6` we will make logging to wandb an option rather than the default behaviour, in order to avoid this type of issues.

**Closed by yannbouteiller** 2023-10-29 19:49 UTC
